nome = str(input('Digite seu nome completo: ')).strip()
print('Seu nome com todas as letras maiusculas é', nome.upper())
print('Seu nome com todas as letras minusculas é', nome.lower())
print('Seu nome contem {} letras.'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))
